name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-15
    strategy:
      matrix:
        run-config:
          - { scheme: 'Lindenmayer-Package', destination: 'platform=iOS Simulator,OS=15.5,name=iPhone 8' }
          - { scheme: 'Lindenmayer-Package', destination: 'platform=macOS' }

    steps:
    - uses: actions/checkout@v4

    - name: Show Build SDK
      run: xcodebuild -showsdks

    - name: List available schemes
      run: xcodebuild -list

    - name: Show Build Settings
      run: xcodebuild -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings

    - name: Show Available Destinations
      run: xcodebuild -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

    - name: Build and Test
      run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary

    # - name: DocBuild
    #   run: xcodebuild docbuild -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -derivedDataPath /tmp/docbuild
