name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11
    strategy:
      matrix:
        run-config:
          - { scheme: 'Lindenmayer-Package', destination: 'platform=iOS Simulator,OS=15.0,name=iPhone 8' }
          - { scheme: 'Lindenmayer', destination: 'platform=macOS,arch=x86_64' }
          #- { scheme: 'LindenmayerViews', destination: 'platform=iOS Simulator,OS=15.0,name=iPhone 8' }
# sdk: -sdk iphonesimulator15.0, -sdk macosx12.0, -sdk appletvsimulator15.0
    steps:
    - uses: actions/checkout@v2

    - name: Show Build SDK
      run: xcodebuild -showsdks

    - name: List available schemes
      run: xcodebuild -list

    - name: Show Build Settings
      run: xcodebuild -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings

    - name: Show Available Destinations
      run: xcodebuild -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

    - name: Build
      run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
